apiVersion: apps/v1
kind: Deployment
metadata:
  name: teste-cobasi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: teste-cobasi
  template:
    metadata:
      labels:
        app: teste-cobasi
    spec:
      containers:
        - name: teste-cobasi
          image: lucascorrea99/cobasi-lucas
          ports:
            - containerPort: 80