apiVersion: v1
kind: Service
metadata:
  name: svc-teste-cobasi
spec:
  type: NodePort
  selector:
    app: teste-cobasi
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
      nodePort: 31000